# This file was automatically generated by bifcl from /root/KafkaLogger-master/src/kafkawriter.bif (plugin mode).

export {
module KafkaLogger;


 
 
 

 

 

} # end of export section
module GLOBAL;
